language: ruby

rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

env:
  - ON_TRAVIS_CI=yes

install: 'gem install bundler -v ">= 1.12" && bundle install --retry=10'

script: 'bundle exec rake rubocop && bundle exec bin/nagios-promoo version'

sudo: false
